FROM 546726916200.dkr.ecr.ap-south-1.amazonaws.com/bharatpe/custome-java-8:1.0 AS java-build
LABEL name="abhinay"

WORKDIR /app 
COPY pom.xml .
RUN mvn clean dependency:go-offline
COPY . .
RUN mvn clean package -Dmaven.test.skip=true #TODO: remove skiptest


FROM 546726916200.dkr.ecr.ap-south-1.amazonaws.com/bharatpe/custome-java-8:1.0
COPY --from=java-build /app/target/*.jar /app/app.jar
#COPY --from=java-build /app/newrelic.yml /
#COPY --from=java-build /app/newrelic.yml /app/newrelic.yml
RUN mkdir -p /data/bbps-recon/
#RUN wget https://bharatpe-cdn.s3.ap-south-1.amazonaws.com/infra/apm-agent.jar
#RUN wget https://bharatpe-cdn.s3.ap-south-1.amazonaws.com/infra/newrelic.jar
#ENTRYPOINT ["java","-javaagent:apm-agent.jar","-javaagent:newrelic.jar","-Duser.timezone=IST","-Dspring.profiles.active=${PROFILE}","-jar","/app/app.jar"]
ENTRYPOINT ["java","-Duser.timezone=IST","-Dspring.profiles.active=${PROFILE}","-jar", "/app/app.jar"]
