# super.key=&E)H@McQfTjWnZr4u7w!z%C*F-JaNdRg
super.key=dRgUkXp2s5u8x/A?D(G+KbPeShVmYq3t
spring.datasource.jdbcUrl=jdbc:mysql://localhost:3306/bharatpenew
server.port=9091
spring.datasource.username=root
spring.datasource.password=Yogi@bharatpe23*
spring.bpnewmaster.username=root
spring.bpnewmaster.password=Yogi@bharatpe23*
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.bpnewmaster.jdbcUrl=jdbc:mysql://localhost:3306/bharatpenew
spring.bpnewmaster.driver-class-name=com.mysql.cj.jdbc.Driver
spring.bpnewmaster.poolName=BPNewMasterDBConnectionPool
spring.slave.jdbcUrl=jdbc:mysql://localhost:3306/bharatpenew
spring.slave.driver-class-name=com.mysql.jdbc.Driver
spring.slave.poolName=SlaveDBConnectionPool
spring.query.jdbcUrl=jdbc:mysql://localhost:3306/bharatpenew?useSSL=false&zeroDateTimeBehavior=convertToNull
spring.query.driver-class-name=com.mysql.cj.jdbc.Driver
spring.query.poolName=QueryDBConnectionPool
spring.query.maximumPoolSize=50
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=1
http.max.total=300
http.max.per.route=200
http.connect.timeout=10000
http.connection.request.timeout=10000
http.read.timeout=10000
http.idle.connection.timeout=60000
push.notification.google.key=AAAAoLytUlg:APA91bEtdXQK6Iyawl9wZWvMXlyQJNOznVIEErS-ZSQS3n4JE0RQRfS7amO3VQXfGnHgMC2nsbkgZqKqbZCCwT5c9FpHY-OO_k-iWTNlWRKRIjMEMNb_HtruEsG7ZXGhl7Y7zPI0zM0D
aws.s3.bucket=loan-document
aws.s3.region=ap-south-1
aws.s3.loan.agreement.bucket=bharatpe-agreement
aws.s3.bucket.kyc.documents=bharatpe-fos/kyc/production
whatsapp.gupshup.userid=2000186647
whatsapp.gupshup.password=sFcwXIZqC
enach.provider=TECHPROCESS
enach.digio.authorization=Basic QUlMQkgyS0dXOVVWNlBaVzNaVkhaMjNLUFJDU1VEWDc6R01XSDlVVVdMRlVHTk85SFU5UUhHTUNUQ0ZJSkZRT1g=
kafka.servers=b-2.stgapps.apeqyd.c4.kafka.ap-south-1.amazonaws.com:9092,b-1.stgapps.apeqyd.c4.kafka.ap-south-1.amazonaws.com:9092
kafka.topic.lending.payout=lending.application.payout
kafka.topic.loyalty.service=loyalty
loyalty.threadpool.size=5
loyalty.service.endpoint=http://payout.bharatpe.io/yesbank/upi/process_cashback/loyalty/loyalty.php
create.vpa.endpoint=https://api.bharatpe.io/startTxn
internal.merchant.id=5361311
liquiloan.secret=12685FACEACF3
aws.s3.bucket_bill=bharatpe-staging/creditline-bills
aws.s3.creditline.bucket=creditline-document
aws.s3.lending.ekyc.bucket=lending-ekyc
payment.service.host=https://sendmoney.bharatpe.io
signzy.url=https://preproduction.signzy.tech/api
signzy.user=bharatpe_test
signzy.password=78=I!Ih7-HLFrl@I?icU
internal.credit.merchant.id=1048906
liquiloans.createLead.api=https://demo-backend.liquiloan.io/api/apiintegration/v2/CreateLeadV2
liquiloan.sid=SI00989
upiPayment.cancel.endpoint=https://api.bharatpe.io/cancelTxn
upiPayment.statusCheck.endpoint=https://api.bharatpe.io/checkTxn
cl.deeplink=bharatpe://dynamic?key=credit-line-dev
merchant.partialUpdate.api=https://merchant.bharatpe.io/merchant/v1/partialupdate

delayed.queue.enabled=true
delayed.queue.redis.host=stg-redis-stg-utils-master.stg-utils.svc.cluster.local
delayed.queue.redis.port=6379
APP.NAME=LENDING

bpnach.register.endpoint=https://api-nach.bharatpe.io/mendate/register

logging.exclude.urls=actuator

#crif config
crif.userId=resilient.bbcuat@bharatpe.com
crif.password=5B5C7B20C31A32CCC480F5B1B400EEF3B06C6ED8
crif.customerId=DTC0000080
crif.appId=aO!$5D^&rQO!ty&&R!*H^@aR*
crif.stage1.url=https://test.crifhighmark.com/Inquiry/do.getSecureService/DTC/initiate
crif.stage2.url=https://test.crifhighmark.com/Inquiry/do.getSecureService/DTC/response

collect.vpa.endpoint=https://api.bharatpe.io/collect
create.van.url=https://api.bharatpe.io/internal/virtualAccount/create
bpnach.endpoint=https://api-nach.bharatpe.io
merchantinfo.endpoint=https://api-merchant.bharatpe.io/merchant/v1/internalclient/merchantinfo
lending.global.endpoint=https://api-lending-global.bharatpe.io
monget.api.dump=https://api-monget.bharatpe.io/app_details/get-dump
redis.server=stg-redis-stg-utils-master.stg-utils.svc.cluster.local
lending.refund.endpoint=http://api-lending-payout.bharatpe.io
loan.details.url=https://lending.bharatpe.io/lending/loanDetails
loan.redemption.topic=bharatpe.club.reward
club.url=https://api-bpclub.bharatpe.io/bharatpe-club/club-member
send.otp.client.name=LENDING
lending.otp.endpoint=http://otp-uat.bharatpe.in/otp/v1/generateotp
lending.verifyOtp.endpoint=http://otp-uat.bharatpe.in/otp/v1/verifyotp
send.otp.purpose=lending
send.otp.source=web
sendgrid.mail.password=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
sendgrid.mail.userId=apikey
NBFC_URL=https://api-nbfc.bharatpe.io/api/v1/loan
NBFC_SIGN_URL=https://api-nbfc.bharatpe.io/api/v1/signLoanDocs
salesdashboard.fos.attribution=https://api-sales.bharatpe.io
monget.generic.url=https://api-monget.bharatpe.io/app_details/get-data
api.notification_service.client=LENDING
api.notification_service.url=https://api-notification.bharatpe.io/api
# pg.url=https://payment-gateway-pp.bharatpe.io
pg.url=https://payment-gateway.bharatpe.co.in
kyc.service.base.url=https://api-kaas.bharatpe.io
new.loan.deeplink=bharatpe://dynamic?key=easy-loans
kyc.deeplink=bharatpe://dynamic?key=kaas&product=LOAN&version=v2
kyc.revalidation.deeplink=bharatpe://dynamic?key=kaas&product=LOAN&version=v2&rekyc=true
kyc.loan.deeplink=bharatpe://dynamic?key=easy-loans-dev
credit.card.base.url=https://credit-card.bharatpe.io
gold.loan.base.url=https://api-gold-loan.bharatpe.io
merchant.service.client=LENDING
topup.loan.enabled=true
fos.task.enabled=true
ds.image.validation.url=http://ds-ml-server-prod-service/img_infer
ds.image.validation.user=ds-user
ds.image.validation.pass=ds@bharatpe123
disbursal.lender.default=LIQUILOANS_NBFC
disbursal.lender.io.topup=LIQUILOANS_NBFC
crm.contact.bucket.name=merchant-phonebook
crm.contact.bucket.region=us-west-2
loan.details.refresh.window=15
spring.slave.username=root
spring.slave.password=Yogi@bharatpe23*
spring.query.username=root
spring.query.password=Yogi@bharatpe23*
bureau.base.url=https://bureau-response-pp.bharatpe.in
club.url.v2=https://api-bpclub.bharatpe.io/v2/bharatpe-club/club-member
eligibility.refresh.window=1
de.merchant.summary.url=https://de-merchant-lending.bharatpe.in/merchant_score
merchant.service.host=https://api-merchant.bharatpe.io
merchant.service.secret=JOXwCW/8emHb2KfY7/TBW15JMd6VUzl4Vjx3+WzhymvZdJTgxUvdIuRwMD1FKyCZ
# merchant.service.secret=YUS7fvnlKLmHc0e+GBobswaL7xsYW3aaOGiDn54SHeBIJAkyhSuA/ZyYq1p/3U84
de.merchant.score.url=https://de-merchant-lending.bharatpe.in/merchant_bpscore
partners.base.url=http://channel-finance-prod-service
lending.payout.base.url=http://lending-refund-incentive.bharatpe.io
enach.base.url=https://api-nach.bharatpe.io
bharat.swipe.base.url=http://swipe.bharatpe.io
club.id.url=https://api-bpclub.bharatpe.io/v2/bp-club/club-member
de.merchant.lending.base.url=https://de-merchant-lending.bharatpe.in
liquiloan.nbfc.secret=C27C59C879112B7E
liquiloan.p2p.secret=2ACB12B639AB6D4F
liquiloan.p2pof.secret=3F88FDC8D4EB1
delhivery.address.validation.url=https://prod-ext-addfix-addvalid.delhivery.com/address_validation
delhivery.address.validation.key=86AmTT8jjz9DVaexaMAhp5uuTLhE307J2rqt2xu9
kfs.template.notification="Dear {Merchant Name}, \n\nCongratulations! \nAs per your request, your loan applied through Bharatpe app has been disbursed into your account. \nKindly click on the links below for further details and loan-related documents. \n\n- Click to check Loan Agreement {{Link 1}} \n- Click to check the Key Fact statement {{Link 2}}"
kfs.sms.notification=KFS_SMS_NOTIFICATION
kfs.wp.notification=KFS_WP_NOTIFICATION
notification.topic=notification_service
role.arn=arn:aws:iam::705292844388:role/prod-s3-assume-role
role.session.name=prod-s3-assume-role
nbfc.service.base.url=https://api-nbfc.bharatpe.io
disbursal_target=1500000
aws.s3.role.arn=arn:aws:iam::705292844388:role/prod-s3-assume-role
aws.s3.role.session.name=lending-uat-session
aws.s3.credentials.accessKey=AKIA2INV2XVSLUEBQ4DH
aws.s3.credentials.secretKey=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
aws.temp.cred.expiry.duration.minute=15
aws.temp.cred.cache.duration.minute=10
pg.percent=20
merchant.references.min.score=18
ds.reference.base.url=https://ds-contacts-service.bharatpe.in
de.reference.base.url=https://de-merchant-lending.bharatpe.in
payout2.service.url.endpoint=https://payout-2.bharatpe.io
clevertap.account.id=R55-Z97-655Z
clevertap.account.passcode=ABDC
clevertap.api.url=https://in1.api.clevertap.com/1/upload
compute.eligibility.from.prod=false
topup.rollout.percent=100
merchant.confidence.score.url
lending.edi.model=6
lender.change.enabled=true
nbfc.baseurl.v3.api=https://api-nbfc.bharatpe.io/
whitelisted.topup.lenders=LDC
aws.s3.credentials=ABCD
gst_offer_lender=LIQUILOANS_P2P
age.check.lenders=ABFL,PIRAMAL
abfl.kafka.enabled=false
abfl.rollout.percent=100
abfl.bre.topic=invoke_bre
abfl.bre.callback.topic=bureau-callback
abfl.dataupload.topic=invoke_data_upload
abfl.drawdown.callback.topic=drawdown-callback
abfl.kyc.topic=invoke_kyc
abfl.kyc.callback.topic=kyc-callback
abfl.sanction.topic=invoke_sanction
abfl.sanction.callback.topic=sanction-callback
invoke.env=prod
loan.payment.order.pending.transaction.time.window=30
fos.nach.percent=20
lender.assign.rollout=100
createLeadUrl=api/v3/lender/create-lead
updateLeadUrl=api/v3/lender/update-lead
nbfcDocUploadUrl=api/v3/lender/document-upload
riskDecisionUrl=api/v3/lender/bureau-check
ds.api.url=http://ds-lending.internal-bp.com
eligiblity.iframe.enabled=true
eligiblity.iframe.cache.time.minutes=1
upi.percent=10
sid.threshold=0
env.value=stage
sid.rollout.percent=