spring.datasource.url=jdbc:mysql://pre-stage-db.cfbhlosmfpat.us-west-2.rds.amazonaws.com:3306/bharatpenew
spring.datasource.username=root
spring.datasource.password=BhAraTPe231
server.port=9091
enach.provider=techprocess
enach.digio.authorization=Basic QUlMQkgyS0dXOVVWNlBaVzNaVkhaMjNLUFJDU1VEWDc6R01XSDlVVVdMRlVHTk85SFU5UUhHTUNUQ0ZJSkZRT1g=
kafka.servers=54.203.220.158:9092
kafka.topic.lending.payout=lending.application.payout
kafka.topic.loyalty.service=loyalty
create.vpa.endpoint=http://api.bharatpe.io/startTxn

loyalty.threadpool.size=20
loyalty.service.endpoint=http://payout.bharatpe.in/yesbank/upi/process_cashback/loyalty/loyalty.php
liquiloan.secret=1C76134A2E224

aws.s3.bucket=creditline-document
aws.s3.bucket_bill=bharatpe-staging/creditline-bills
aws.s3.credentials.accessKey=AKIA2INV2XVSLUEBQ4DH
aws.s3.credentials.secretKey=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
aws.s3.region=ap-south-1
aws.s3.lending.ekyc.bucket=lending-ekyc
aws.s3.creditline.bucket=creditline-document
aws.s3.loan.agreement.bucket=bharatpe-agreement
payment.service.host=https://sendmoney.bharatpe.io
internal.merchant.id=1048906
signzy.url=https://preproduction.signzy.tech/api
signzy.user=bharatpe_test
signzy.password=78=I!Ih7-HLFrl@I?icU
internal.credit.merchant.id=1048906
upiPayment.cancel.endpoint=https://api.bharatpe.io/cancelTxn
upiPayment.statusCheck.endpoint=https://api.bharatpe.io/checkTxn
liquiloans.createLead.api=https://demo-backend.liquiloan.in/api/apiintegration/v2/CreateLeadV2
liquiloan.sid=SI00989
cl.deeplink=bharatpe://dynamic?key=credit-line-dev

#Delayed queue config
delayed.queue.enabled=true
delayed.queue.redis.host=merchant-otp-stage-redis.segvmm.0001.usw2.cache.amazonaws.com
delayed.queue.redis.port=6379
APP.NAME=LENDING

bpnach.register.endpoint=https://api-nach.bharatpe.io/mendate/register

logging.exclude.urls=actuator

#crif config
crif.userId=resilient.bbcuat@bharatpe.com
crif.password=5B5C7B20C31A32CCC480F5B1B400EEF3B06C6ED8
crif.customerId=DTC0000080
crif.appId=aO!$5D^&rQO!ty&&R!*H^@aR*
crif.stage1.url=https://test.crifhighmark.com/Inquiry/do.getSecureService/DTC/initiate
crif.stage2.url=https://test.crifhighmark.com/Inquiry/do.getSecureService/DTC/response

collect.vpa.endpoint=https://api.bharatpe.io/collect
create.van.url=https://api.bharatpe.io/internal/virtualAccount/create