spring.datasource.host=localhost
spring.datasource.url=jdbc:mysql://localhost:3306/bharatpe
spring.datasource.username=root
spring.datasource.password=ronaldinho@kai
spring.datasource.driver-class-name=com.mysql.jdbc.Driver