spring.datasource.url=jdbc:mysql://root@localhost:3306/lendingService?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

spring.datasource.jdbcUrl=jdbc:mysql://root@localhost:3306/lendingService?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

server.port=9091

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.bpnewmaster.jdbcUrl=jdbc:mysql://root@localhost:3306/lendingService?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

spring.bpnewmaster.driver-class-name=com.mysql.cj.jdbc.Driver

spring.bpnewmaster.poolName=BPNewMasterDBConnectionPool

spring.slave.jdbcUrl=jdbc:mysql://root@localhost:3306/lendingService?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

spring.slave.driver-class-name=com.mysql.jdbc.Driver

spring.query.jdbcUrl=jdbc:mysql://root@localhost:3306/lendingService?useSSL=false&allowMultiQueries=true&serverTimezone=UTC

spring.query.driver-class-name=com.mysql.cj.jdbc.Driver

spring.query.poolName=QueryDBConnectionPool

spring.datasource.hikari.maximum-pool-size=1

spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.connection-timeout=20000

spring.datasource.poolName=MasterDBConnectionPool

spring.datasource.maximumPoolSize=1

spring.datasource.minimumIdle=1

spring.datasource.connectionTimeout=20000

spring.datasource.maximum-pool-size=1

spring.datasource.minimum-idle=1

spring.datasource.connection-timeout=20000

spring.slave.poolName=SlaveDBConnectionPool

spring.slave.maximumPoolSize=1

spring.slave.minimumIdle=1

spring.slave.connectionTimeout=20000

spring.slave.maximum-pool-size=1

spring.slave.minimum-idle=1

spring.slave.connection-timeout=20000

hibernate.hikari.idleTimeout=20000

logging.level.com.zaxxer.hikari.pool.HikariPool=DEBUG

http.max.total=500

http.max.per.route=200

http.connect.timeout=10000

http.connection.request.timeout=10000

http.read.timeout=10000

http.idle.connection.timeout=60000

push.notification.google.key=AAAAoLytUlg:APA91bEtdXQK6Iyawl9wZWvMXlyQJNOznVIEErS-ZSQS3n4JE0RQRfS7amO3VQXfGnHgMC2nsbkgZqKqbZCCwT5c9FpHY-OO_k-iWTNlWRKRIjMEMNb_HtruEsG7ZXGhl7Y7zPI0zM0D

aws.s3.bucket=loan-document

aws.s3.region=ap-south-1

aws.s3.loan.agreement.bucket=bharatpe-agreement

aws.s3.bucket.kyc.documents=bharatpe-fos/kyc/production

whatsapp.gupshup.userid=2000186647

whatsapp.gupshup.password=sFcwXIZqC

enach.provider=TECHPROCESS

enach.digio.authorization=Basic QUlMQkgyS0dXOVVWNlBaVzNaVkhaMjNLUFJDU1VEWDc6R01XSDlVVVdMRlVHTk85SFU5UUhHTUNUQ0ZJSkZRT1g=

kafka.servers=172.31.32.8:9092,172.31.40.234:9092,172.31.43.107:9092,172.31.43.183:9092,172.31.36.144:9092,172.31.33.69:9092,172.31.40.97:9092,172.31.40.200:9092,172.31.32.87:9092

kafka.topic.lending.payout=lending.application.payout

kafka.topic.loyalty.service=loyalty

loyalty.threadpool.size=5

loyalty.service.endpoint=http://payout.bharatpe.in/yesbank/upi/process_cashback/loyalty/loyalty.php

create.vpa.endpoint=http://api.bharatpe.in/startTxn

internal.merchant.id=5361311

liquiloan.secret=12685FACEACF3

aws.s3.bucket_bill=bharatpe-staging/creditline-bills

aws.s3.creditline.bucket=creditline-document

aws.s3.lending.ekyc.bucket=lending-ekyc

payment.service.host=https://sendmoney.bharatpe.in

signzy.url=https://signzy.tech/api

signzy.user=bharatpe_lending_prod

signzy.password=YMgVUQqbqBv0um3ckEaP

internal.credit.merchant.id=5423257

liquiloan.sid=S002093

liquiloans.createLead.api=https://api.liquiloans.com/api/apiintegration/v2/CreateLeadV2

liquiloans.disbursal.api=https://api.liquiloans.com/api/apiintegration/v2/CreateDisbursal

upiPayment.cancel.endpoint=http://api.bharatpe.in/cancelTxn

upiPayment.statusCheck.endpoint=http://api.bharatpe.in/checkTxn

cl.deeplink=bharatpe://dynamic?key=credit-line

delayed.queue.enabled=true

delayed.queue.redis.host=banking-prod-redis.ysqudk.0001.aps1.cache.amazonaws.com

delayed.queue.redis.port=6379

APP.NAME=LENDING

bpnach.register.endpoint=http://api-nach.bharatpe.in/mendate/register

logging.exclude.urls=actuator

sentry.dsn=https://d8a663b187804399b67acec80edfc0fc@sentry-new.bharatpe.in/4

merchant.partialUpdate.api=http://api-merchant.bharatpe.in/merchant/v1/partialupdate

crif.userId=resilient.bbcprod@bharatpe.com

crif.password=0178386643035E05DBAD90911904B39A3E9C3580

crif.customerId=DTC0000095

crif.appId=eO!$8D!#rQ7!uj@&R(^H^*aR#

crif.stage1.url=https://cir.crifhighmark.com/Inquiry/do.getSecureService/DTC/initiate

crif.stage2.url=https://cir.crifhighmark.com/Inquiry/do.getSecureService/DTC/response

collect.vpa.endpoint=http://api.bharatpe.in/collect

create.van.url=http://api.bharatpe.in/internal/virtualAccount/create

bpnach.endpoint=https://api-nach.bharatpe.in

merchantinfo.endpoint=http://api-merchant.bharatpe.in/merchant/v1/internalclient/merchantinfo

lending.global.endpoint=http://api-lending-global.bharatpe.in

monget.api.dump=https://api-monget.bharatpe.in/app_details/get-dump

redis.server=lending.vok9kf.0001.aps1.cache.amazonaws.com

lending.refund.endpoint=http://lending-refund-incentive.bharatpe.in

loan.details.url=http://lending.bharatpe.in/lending/loanDetails

loan.redemption.topic=bharatpe.club.reward

club.url=http://api-bpclub.bharatpe.in/bharatpe-club/club-member

send.otp.client.name=LENDING

lending.otp.endpoint=https://otp.bharatpe.in/otp/v1/generateotp

lending.verifyOtp.endpoint=https://otp.bharatpe.in/otp/v1/verifyotp

send.otp.purpose=lending

send.otp.source=web

sendgrid.mail.password=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

sendgrid.mail.userId=apikey

NBFC_URL=https://api-nbfc.bharatpe.in/api/v1/loan

salesdashboard.fos.attribution=https://api-sales.bharatpe.in

monget.generic.url=https://api-monget.bharatpe.in/app_details/get-data

api.notification_service.client=LENDING

api.notification_service.url=http://api-notification.bharatpe.in/api

#pg.url=http://payment-gateway.bharatpe.in
pg.url=https://payment-gateway.bharatpe.co.in

kyc.service.base.url=http://api-kaas.bharatpe.in

new.loan.deeplink=bharatpe://dynamic?key=easy-loans

kyc.deeplink=bharatpe://dynamic?key=kaas&product=LOAN&version=v2

kyc.loan.deeplink=bharatpe://dynamic?key=easy-loans

kyc.revalidation.deeplink=bharatpe://dynamic?key=kaas&product=LOAN&version=v2&rekyc=true

credit.card.base.url=http://credit-card.bharatpe.in

gold.loan.base.url=http://api-gold-loan.bharatpe.in

topup.loan.enabled=true

fos.task.enabled=true

ds.image.validation.url=http://ds-ml.bharatpe.in/img_infer

ds.image.validation.user=ds-user

ds.image.validation.pass=ds@bharatpe123

delhivery.address.validation.key=86AmTT8jjz9DVaexaMAhp5uuTLhE307J2rqt2xu9

delhivery.address.validation.url=https://prod-ext-addfix-addvalid.delhivery.com/address_validation

api.calling.nimbus.url=http://103.119.220.157/nimbusdial_admin/non_agent_api.php

api.calling.nimbus.user=BPAPI

api.calling.nimbus.password=NimPeINDIA

disbursal.lender.default=LIQUILOANS_NBFC

disbursal.lender.io.topup=LIQUILOANS_NBFC

crm.contact.bucket.name=merchant-phonebook

crm.contact.bucket.region=us-west-2

eligibility.refresh.window=1

loan.details.refresh.window=15

#spring.slave.username=api-lending
#
#spring.slave.password=RocksDB%$^12(*
#
#spring.query.username=easyloan_read
#
#spring.query.password=ky5s3^kt6)h2

bureau.base.url=http://bureau-response.bharatpe.in

de.merchant.summary.url=http://de-merchant-lending.bharatpe.in/merchant_score

club.url.v2=http://api-bpclub.bharatpe.in/v2/bharatpe-club/club-member

merchant.service.host=http://api-merchant.bharatpe.in

merchant.service.client=LENDING

merchant.service.secret=YUS7fvnlKLmHc0e+GBobswaL7xsYW3aaOGiDn54SHeBIJAkyhSuA/ZyYq1p/3U84

partners.base.url=http://channel-finance-prod2-service

de.merchant.score.url=http://de-merchant-lending.bharatpe.in/merchant_bpscore

lending.payout.base.url=http://lending-refund-incentive.bharatpe.in

enach.base.url=http://api-nach.bharatpe.in

bharat.swipe.base.url=http://swipe.bharatpe.in

de.merchant.lending.base.url=http://de-merchant-lending.bharatpe.in

liquiloan.nbfc.secret=C27C59C879112B7E

liquiloan.p2p.secret=2ACB12B639AB6D4F

liquiloan.p2pof.secret=3F88FDC8D4EB1

kfs.template.notification="Dear {Merchant Name}, \n\nCongratulations! \nAs per your request , your loan applied through Bharatpe app has been disbursed into your account. \nKindly click on the links below for further details and loan-related documents. \n\n- Click to check Loan Agreement {{Link 1}} \n- Click to check the Key Fact statement {{Link 2}}"

kfs.sms.notification=KFS_SMS_NOTIFICATION

kfs.wp.notification=KFS_WP_NOTIFICATION

notification.topic=notification_service

nbfc.service.base.url=https://api-nbfc.bharatpe.in

sign_loan_docs.consumer.enabled=false

#####################

pg.android.version=325

pg.percent=100

upi.percent=10

merchant.references.min.score=18

ds.reference.base.url=https://ds-contacts-service.bharatpe.in

de.reference.base.url=http://de-merchant-lending.bharatpe.in

kafka.consumerGroup.nbfc.payout.status.callback.enabled=false

payout2.service.url.endpoint=https://payout-2.bharatpe.in

disbursal_target=700000

clevertap.account.id=R55-Z97-655Z

clevertap.account.passcode=ETO-ZUX-OPKL

clevertap.api.url=https://in1.api.clevertap.com/1/upload

compute.eligibility.from.prod=true

aws.s3.role.arn=arn:aws:iam::705292844388:role/prod-s3-assume-role

aws.s3.role.session.name=lending

aws.temp.cred.expiry.duration.minute=15

aws.temp.cred.cache.duration.minute=11

whitelisted.topup.lenders=LDC,LIQUILOANS_P2P,LIQUILOANS_NBFC,LIQUILOANS_P2P_OF

topup.rollout.percent=100

merchant.confidence.score.url=http://de-merchant-lending.bharatpe.in/GetMerchantConfidenceScore

lending.edi.model=6

lender.change.enabled=true

nbfc.baseurl.v3.api=https://api-nbfc.bharatpe.in/

abfl.rollout.percent=100

abfl.bre.topic=invoke_bre

abfl.bre.callback.topic=bureau-callback

abfl.dataupload.topic=invoke_data_upload

abfl.drawdown.callback.topic=drawdown-callback

abfl.kyc.topic=invoke_kyc

abfl.kyc.callback.topic=kyc-callback

abfl.sanction.topic=invoke_sanction

abfl.sanction.callback.topic=sanction-callback

age.check.lenders=ABFL

abfl.kafka.enabled=false

invoke.env=prod

loan.payment.order.pending.transaction.time.window=30

fos.nach.percent=20

aws.s3.credentials=lending-keyRotation

super.key=&E)H@McQfTjWnZr4u7w!z%C*F-JaNdRg

gst_offer_lender=LIQUILOANS_P2P

master.key=5QvzFrPGSB/M6WSFcExJKsc8pffkTGHVBSswj0TyVS1fo8rZnreYMzQjpAw++dfX

lender.assign.rollout=100

ds.api.url=

sid.threshold=

sid.rollout.percent=100

finance-utils.base.url=

environment.value=stage

offer.modified.eligible.lender = PIRAMAL