spring.datasource.url=jdbc:mysql://pre-stage-db.cfbhlosmfpat.us-west-2.rds.amazonaws.com:3306/bharatpenew
spring.datasource.username=root
spring.datasource.password=BhAraTPe231
server.port=9090
enach.provider=techprocess
enach.digio.authorization=Basic QUlMQkgyS0dXOVVWNlBaVzNaVkhaMjNLUFJDU1VEWDc6R01XSDlVVVdMRlVHTk85SFU5UUhHTUNUQ0ZJSkZRT1g=
kafka.servers=54.203.220.158:9092
kafka.topic.lending.payout=lending.application.payout
loyalty.threadpool.size=20
loyalty.service.endpoint=http://payout.bharatpe.in/yesbank/upi/process_cashback/loyalty/loyalty.php