package com.bharatpe.lending.loanV3.enums.piramal;

public enum FeeType {
    STAMP_DUTY ,PROCESSING_FEE, PRE_PROCESSING_FEE ,STAMP_CHARGE, PROCESSING_FEES, OVERDUE_INTEREST_ON_DEFAULT_INSTALL, LATE_PAYMENT_INTEREST, CHI7486, UNKNOWN
}
