package com.bharatpe.lending.loanV3.revamp.enums;

public enum LendingViewStates {
    PAN_PIN_PAGE, PERMISSIONS_PAGE, OFFER_PAGE, INELIGIBLE_PAGE, SHOP_DETAILS_PAGE,
    SHOP_PICTURES_PAGE, KYC_PAGE, LENDER_EVALUATION_PAGE, REFERENCE_PAGE, AGREEMENT_PAGE,
    KEY_FACTOR_STATEMENT_PAGE,  ENACH_PAGE, ENACH_BANK_PAGE,  APPLICATION_STATUS_PAGE, KYC_ROUTE_TO_ELIGIBILITY, LENDER_TOPUP_REJECTED,
    TOPUP_OFFER_PAGE, TOPUP_AGREEMENT_PAGE, LOAN_STATEMENT_PAGE, REPAYMENT_PAGE, PAYMENT_STATUS_PAGE, USER_VALIDATION_PAGE, ALL_LOAN_PAGE,
    RTE_PIN_PAGE;
}
