package com.bharatpe.lending.ai.dto;

import com.bharatpe.common.entities.LendingApplication;
import com.bharatpe.common.enums.RejectionStage;
import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.Data;
import lombok.EqualsAndHashCode;

import java.util.Date;

@Data
@EqualsAndHashCode(callSuper = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class AiLendingApplication extends AiBaseEntity {
    private Long merchantId;
    private String shopNumber;
    private String streetAddress;
    private String area;
    private String landmark;
    private Long pincode;
    private String city;
    private String state;
    private String businessName;
    private Double loanAmount;
    private Double edi;
    private Double ioEdi;
    private String category;
    private Double processingFee;
    private Double repayment;
    private String tenure;
    private Integer tenureInMonths;
    private Long payableDays;
    private Integer ioPayableDays;
    private Integer ediFreeDays;
    private Double interestRate;
    private String status;
    private String latitude;
    private String longitude;
    private String ip;
    private String externalLoanId;
    private String nbfcId;
    private String manualKyc;
    private String manualKycNotes;
    private String manualKycAdditionalInfo;
    private String manualCibil;
    private String manualCibilNotes;
    private String manualCibilAdditionalInfo;
    private String manualCibilDeviation;
    private String manualCibilDeviationOtherReason;
    private String physicalVerificationStatus;
    private String physicalVerificationAdditionalInfo;
    private String physicalVerificationNotes;
    private String sendToNbfc;
    private String loanDisbursalStatus;
    private Long approvedBy;
    private String lender;
    private int agreement;
    private Date agreementAt;
    private String loanConstruct;
    private String mode;
    private Double disbursalAmount;
    private Integer totalLoansCount;
    private String nachType;
    private String nachLender;
    private String nachReferenceNumber;
    private String nachStatus;
    private String nachBankComment;
    private String loanType;
    private String alternateName;
    private String verifyOcr;
    private Date disburseTimestamp;
    private String disbursalPartner;
    private Date kycApprovedDate;
    private Date cibilApprovedDate;
    private Date physicalApprovedDate;
    private String accountType;
    private Date kycAssignedAt;
    private Date assignedAt;
    private Date cpvSubmitTimestamp;
    private Date cpvCloseDate;
    private Date nbfcSendDate;
    private String responseCode;
    private Long cpvAgentId;
    private String manualKycReason;
    private String manualCibilReason;
    private String physicalReason;
    private String ckycId;
    private String ckycStatus;
    private String ckycRejectionReason;
    private Date ckycDate;
    private String lmsStage;
    private String merchantName;
    private String lmsAgentReferralCode;
    private RejectionStage rejectionStage;
    private String rejectionReason;

    public AiLendingApplication(LendingApplication lendingApplication) {
        super(lendingApplication);
        if (lendingApplication != null) {
            this.merchantId = lendingApplication.getMerchantId();
            this.shopNumber = lendingApplication.getShopNumber();
            this.streetAddress = lendingApplication.getStreetAddress();
            this.area = lendingApplication.getArea();
            this.landmark = lendingApplication.getLandmark();
            this.pincode = lendingApplication.getPincode();
            this.city = lendingApplication.getCity();
            this.state = lendingApplication.getState();
            this.businessName = lendingApplication.getBusinessName();
            this.loanAmount = lendingApplication.getLoanAmount();
            this.edi = lendingApplication.getEdi();
            this.ioEdi = lendingApplication.getIoEdi();
            this.category = lendingApplication.getCategory();
            this.processingFee = lendingApplication.getProcessingFee();
            this.repayment = lendingApplication.getRepayment();
            this.tenure = lendingApplication.getTenure();
            this.tenureInMonths = lendingApplication.getTenureInMonths();
            this.payableDays = lendingApplication.getPayableDays();
            this.ioPayableDays = lendingApplication.getIoPayableDays();
            this.ediFreeDays = lendingApplication.getEdiFreeDays();
            this.interestRate = lendingApplication.getInterestRate();
            this.status = lendingApplication.getStatus();
            this.latitude = lendingApplication.getLatitude();
            this.longitude = lendingApplication.getLongitude();
            this.ip = lendingApplication.getIp();
            this.externalLoanId = lendingApplication.getExternalLoanId();
            this.nbfcId = lendingApplication.getNbfcId();
            this.manualKyc = lendingApplication.getManualKyc();
            this.manualKycNotes = lendingApplication.getManualKycNotes();
            this.manualKycAdditionalInfo = lendingApplication.getManualKycAdditionalInfo();
            this.manualCibil = lendingApplication.getManualCibil();
            this.manualCibilNotes = lendingApplication.getManualCibilNotes();
            this.manualCibilAdditionalInfo = lendingApplication.getManualCibilAdditionalInfo();
            this.manualCibilDeviation = lendingApplication.getManualCibilDeviation();
            this.manualCibilDeviationOtherReason = lendingApplication.getManualCibilDeviationOtherReason();
            this.physicalVerificationStatus = lendingApplication.getPhysicalVerificationStatus();
            this.physicalVerificationAdditionalInfo = lendingApplication.getPhysicalVerificationAdditionalInfo();
            this.physicalVerificationNotes = lendingApplication.getPhysicalVerificationNotes();
            this.sendToNbfc = lendingApplication.getSendToNbfc();
            this.loanDisbursalStatus = lendingApplication.getLoanDisbursalStatus();
            this.approvedBy = lendingApplication.getApprovedBy();
            this.lender = lendingApplication.getLender();
            this.agreement = lendingApplication.getAgreement();
            this.agreementAt = lendingApplication.getAgreementAt();
            this.loanConstruct = lendingApplication.getLoanConstruct();
            this.mode = lendingApplication.getMode();
            this.disbursalAmount = lendingApplication.getDisbursalAmount();
            this.totalLoansCount = lendingApplication.getTotalLoansCount();
            this.nachType = lendingApplication.getNachType();
            this.nachLender = lendingApplication.getNachLender();
            this.nachReferenceNumber = lendingApplication.getNachReferenceNumber();
            this.nachStatus = lendingApplication.getNachStatus();
            this.nachBankComment = lendingApplication.getNachBankComment();
            this.loanType = lendingApplication.getLoanType();
            this.alternateName = lendingApplication.getAlternateName();
            this.verifyOcr = lendingApplication.getVerifyOcr();
            this.disburseTimestamp = lendingApplication.getDisburseTimestamp();
            this.disbursalPartner = lendingApplication.getDisbursalPartner();
            this.kycApprovedDate = lendingApplication.getKycApprovedDate();
            this.cibilApprovedDate = lendingApplication.getCibilApprovedDate();
            this.physicalApprovedDate = lendingApplication.getPhysicalApprovedDate();
            this.accountType = lendingApplication.getAccountType();
            this.kycAssignedAt = lendingApplication.getKycAssignedAt();
            this.assignedAt = lendingApplication.getAssignedAt();
            this.cpvSubmitTimestamp = lendingApplication.getCpvSubmitTimestamp();
            this.cpvCloseDate = lendingApplication.getCpvCloseDate();
            this.nbfcSendDate = lendingApplication.getNbfcSendDate();
            this.responseCode = lendingApplication.getResponseCode();
            this.cpvAgentId = lendingApplication.getCpvAgentId();
            this.manualKycReason = lendingApplication.getManualKycReason();
            this.manualCibilReason = lendingApplication.getManualCibilReason();
            this.physicalReason = lendingApplication.getPhysicalReason();
            this.ckycId = lendingApplication.getCkycId();
            this.ckycStatus = lendingApplication.getCkycStatus();
            this.ckycRejectionReason = lendingApplication.getCkycRejectionReason();
            this.ckycDate = lendingApplication.getCkycDate();
            this.lmsStage = lendingApplication.getLmsStage();
            this.merchantName = lendingApplication.getMerchantName();
            this.lmsAgentReferralCode = lendingApplication.getLmsAgentReferralCode();
            this.rejectionStage = lendingApplication.getRejectionStage();
            this.rejectionReason = lendingApplication.getRejectionReason();
        }
    }

}
