package com.bharatpe.lending.enums;

public enum ApplicationDocType {
    KEY_FACTS_STATEMENT_DETAILS,
    KEY_FACTS_STATEMENT_DOC,
    SANCTION_CUM_LOAN_AGREEMENT_DOC,
    ABFL_LETTERHEAD_HEADER,
    ABFL_LETTERHEAD_FOOTER,
    WELCOME_LETTER_DOC,
    HINDON_LETTERHEAD_HEADER,
    HINDON_LETTERHEAD_FOOTER

}
