package com.bharatpe.lending.enums;

public enum BankStatementRejectReason {
    ACCOUNT_NO_MISMATCH, ACCOUNT_TYPE_MISMATCH, BANK_STATEMENT_NOT_IN_6_MONTH_PERIOD, GLOBAL_LIMIT_EXCEPTION, GLOBAL_LIMIT_FAILED, BANK_DETAILS_MISSING, FAILED_CALLBACK_STATUS,
    UPLOAD_API_REJECT, OFFER_DOWNGRADE, OFFER_SAME;
}
