package com.bharatpe.lending.enums;

public enum CleverTapEvents {
    LOAN_KYC_VERIFIED_BE,
    LOAN_KYC_INITIATED_BE,
    LOAN_RESUBMIT_COMPLETED,
    LOAN_RESUBMIT_INITIATED,

    LOAN_APPLICATION_INITIATED_BE,

    LOAN_APPLICATION_COMPLETED_BE,

    LOAN_PREAPPROVED_BE,

    LOAN_NACH_COMPLETED_BE,

    RTE_V3_ELIGIBLE,
    RTE_V3_INELIGIBLE,
    RTE_V3_ACTIVE_COMPLETE,
    RTE_V3_ACTIVE_NOT_COMPLETE,
    RTE_V3_ENROLL_DONE,
    RTE_V3_ACTIVE_7DAYS,
    RTE_V3_ACTIVE_12DAYS,
    RTE_V3_ACTIVE_30DAYS,
    RTE_V3_ACTIVE_60DAYS
}
