package com.bharatpe.lending.enums;

public enum CleverTapEvents {
    LOAN_KYC_VERIFIED_BE,
    LOAN_KYC_INITIATED_BE,
    LOAN_RESUBMIT_COMPLETED,
    LOAN_RESUBMIT_INITIATED,

    LOAN_APPLICATION_INITIATED_BE,

    LOAN_APPLICATION_COMPLETED_BE,

    LOAN_PREAPPROVED_BE,

    LOAN_NACH_COMPLETED_BE
}
