package com.bharatpe.lending.enums;

public enum Gst3bRejectReason {
    GLOBAL_LIMIT_EXCEPTION, GLOBAL_LIMIT_FAILED, FAILED_CALLBACK_STATUS, OFFER_SAME, BEYOND_TAT, GST3B_NOT_IN_12_MONTH_PERIOD, PAN_GST_MISMATCHED,
    SENT_OTP_API_FAILED, VERIFY_OTP_API_FAILED, UPLOAD_API_FAILED;
}
