package com.bharatpe.lending.enums;

public enum HomePageCardsState {
    CARD_NOT_APPLICABLE,
    CARD_LOAN_ELIGIBLE,
    CARD_RTE_ELIGIBLE,
    NO_CARD,
    CARD_LOAN_ELIGIBILITY_NOT_CHECKED,
    CARD_RTE_ENROLLED,
    CARD_APPLICATION_CREATED_BUT_NOT_COMPLETED,
    CARD_AGREEMENT_NOT_SIGNED,
    CARD_AGREEMENT_SIGNED_BUT_NACH_NOT_SET,
    CARD_VERIFICATION_IN_PROGRESS,
    CARD_REUPLOAD_DOCUMENTS,
    CARD_DISBURSAL_PENDING,
    CARD_AMOUNT_OVERDUE_DPD,
    CARD_EDI_AUTO_DEBITED,
    CARD_TOPUP_LOAN_OFFER_AMOUNT,
}