package com.bharatpe.lending.enums;

public enum KycDocType {

    ENTITY("ENTITY"),
    SHOP_NAME("SHOP_NAME"),
    SHOP_ADDRESS("SHOP_ADDRESS"),
    ACCOUNT_TYPE("ACCOUNT_TYPE"),
    PAN_NO("PAN_NO"),
    PAN_CARD("PAN_CARD"),
    POA("POA"),
    AADHAAR("AADHAAR"),
    VOTERCARD("VOTERCARD"),
    PASSPORT("PASSPORT"),
    DRIVING_LICENCE("DRIVING_LICENCE"),
    SELFIE("SELFIE"),
    BUSINESSPROOF("BUSINESSPROOF"),
    BUSINESS_PROOF("BUSINESS_PROOF"),
    BUSINESS_PAN("BUSINESS_PAN"),
    BUSINESS_DEED("BUSINESS_DEED"),
    COI("COI"),
    AOI("AOI"),
    EKYC("EKYC"),
    GST("GST"),
    OTHER("OTHER"),
    INDIVIDUAL_PAN("INDIVIDUAL_PAN"),
    UDYOG_AADHAAR("UDYOG_AADHAAR"),
    ELECTRICITY_BILL("ELECTRICITY_BILL"),
    POSTPAID_MOBILE_BILL("POSTPAID_MOBILE_BILL"),
    AOA("AOA"),
    AUTHORITY_LETTER("AUTHORITY_LETTER"),
    AUTHSIGNATORY_PAN("AUTHSIGNATORY_PAN"),
    BOARD_RESOLUTION("BOARD_RESOLUTION"),
    BUSINESSDOCS("BUSINESSDOCS"),
    CANCELLED_CHEQUE("CANCELLED_CHEQUE"),
    CERTIFICATE_OF_INC("CERTIFICATE_OF_INC"),
    CKYC("CKYC"),
    FSSAI_LICENSE("FSSAI_LICENSE"),
    GST_CERTIFICATE("GST_CERTIFICATE"),
    GST_NO("GST_NO"),
    LLP_DEED("LLP_DEED"),
    MCD_CERTFIICATE("MCD_CERTFIICATE"),
    MOA("MOA"),
    PARTNERSHIP_DEED("PARTNERSHIP_DEED"),
    PIPED_GAS_BILL("PIPED_GAS_BILL"),
    REGISTRATION_CERTIFICATE("REGISTRATION_CERTIFICATE"),
    SHOP_AND_ESTABLISHMENT("SHOP_AND_ESTABLISHMENT"),
    SHOP_PICTURE("SHOP_PICTURE"),
    TELEPHONE_BILL("TELEPHONE_BILL"),
    TRUST_DEED("TRUST_DEED"),
    VAT("VAT"),
    WATER_BILL("WATER_BILL"),
    UDYAM_CERTIFICATE("UDYAM_CERTIFICATE");

    String val;

    KycDocType(String val) {
        this.val = val;
    }

    public String getVal() {
        return val;
    }
}
