package com.bharatpe.lending.enums;

public enum Lender {
    LDC, MAMTA, HINDON, LIQUILOANS, LIQUILOANS_NBFC, LIQUILOANS_P2P, LIQUILOANS_P2P_OF, MAMTA0, MAMTA1, MAMTA2, ABFL,PIRAMAL, USFB, TRILLIONLOANS, MUTHOOT, CAPRI;
}
