package com.bharatpe.lending.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum PaymentBank {

    AIRTEL_PAYMENTS_BANK("AIRTEL PAYMENTS BANK"),
    AIRTEL_PAYMENTS_BANK_LTD("AIRTEL PAYMENTS BANK LTD"),
    PAYTM_PAYMENTS_BANK("PAYTM PAYMENTS BANK"),
    PAYTM_PAYMENTS_BANK_LTD("PAYTM PAYMENTS BANK LTD"),
    INDIA_POST_PAYMENTS_BANK("INDIA POST PAYMENTS BANK"),
    INDIA_POST_PAYMENTS_BANK_LTD("INDIA POST PAYMENTS BANK LTD"),
    INDIA_POST_PAYMENT_BANK_LIMITED("INDIA POST PAYMENTS BANK LIMITED"),
    FINO_PAYMENTS_BANK("FINO PAYMENTS BANK"),
    FINO_PAYMENTS_BANK_LTD("FINO PAYMENTS BANK LTD"),
    JIO_PAYMENTS_BANK("JIO PAYMENTS BANK"),
    JIO_PAYMENTS_BANK_LTD("JIO PAYMENTS BANK LTD"),
    NSDL_PAYMENTS_BANK("NSDL PAYMENTS BANK"),
    NSDL_PAYMENTS_BANK_LTD("NSDL PAYMENTS BANK LTD"),
    NSDL_PAYMENTS_BANK_LIMITED("NSDL PAYMENTS BANK LIMITED");







    private String val;
}

//Airtel Payments Bank:
//Fino Payments Bank:
//India Post Payments Bank:
//Paytm Payments Bank:
//Jio Payments Bank:
//NSDL Payments Bank: